### ISSUE TITLE
Merge RFC72 to main branch: Spring Boot Upgrade Part

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#10356]
# 1. Required Before Merging
- [x] Rebase old Pim's branch @haynescd @JREastonMarks 🎉 

## Backend Testing
- [x] Fix all Unit/Integration tests. Sheet to keep track @haynescd @fuzhaoyuan : https://docs.google.com/spreadsheets/d/1NwB3oBEDN2Tzw0Itx0yK83Omg1HBvj3EGml4xa0tg1M/edit#gid=0
 (Make sure they are running, compare against master branch)

## Remote End to End Testing

- [x] Fix Docker image to run in production (related [ticket](https://github.com/cBioPortal/cbioportal/issues/10376)):
    ```
    Caused by: java.lang.NoSuchMethodError: 'java.lang.String javax.servlet.ServletContext.getVirtualServerName()'
        at org.apache.catalina.authenticator.AuthenticatorBase.startInternal(AuthenticatorBase.java:1355) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
        ... 39 common frames omitted
    ```
- [x] Deploy to master.cbioportal.org  or beta.cbioportal.org
    - [x] run remote E2E tests against it (@alisman )

## CI Tests
- [x] Make sure all github actions are passing for backend
  - [x] Integration Tests (@haynescd )
- [x] Github Action Core tests fixed
- [x] CircleCI tests
- [x] Create a demo-rfc72 branch on cbioportal-docker-compose repo (@inodb)
  - [x] Run webapp
  - [x] Load a study in docker compose setup

## Configuration
- [x] Can't have both Microsoft and google auth: https://github.com/cBioPortal/cbioportal/issues/10378
- [x] Migrate these parameters for webapprunner to Tomcat config:
    ```
     -AmaxHttpHeaderSize=16384 -AconnectionTimeout=20000
    ```
    see these spring boot [configuration docs](https://www.baeldung.com/spring-boot-configure-tomcat#3-server-connections).
- [x] Multiple portal.properties files? @haynescd See:
   ![image](https://github.com/cBioPortal/cbioportal/assets/1334004/39a47923-2d45-4251-8c9e-f2d71f44923b)
- [x] Database connection does not seem to be working for this class: https://github.com/cBioPortal/cbioportal/blob/demo-rfc72/core/src/main/java/org/mskcc/cbio/portal/dao/JdbcDataSource.java
- [ ] CORS is missing

## Clean Up
- [ ] Add instructions on how to run in IntelliJ or VSCode or Eclipse
- [x] Update docs on how we're currently running it locally on command line @inodb  
- [x] docker-entrypoint is not running migration @haynescd 

## Authentication
Security XML has been migrated to an annotation based system. There seems to be a separate OAuth implementation from @pvannierop.
- [x] Try social_auth (is it OAuth?)
- [x] Test saml

## Versioning
- [ ] Previously we used [maven-external-version plugin](https://github.com/cBioPortal/maven-external-version) to keep track of the version. It pulls the version from git at compile time and sticks it into the pom. There was a [change](https://github.com/cBioPortal/cbioportal/commit/1630b6bdbe764811133b4f097540e40af473aa1f) to hardcode a version in the pom. Does the maven-external-version plugin still work?

## Dependencies
- [x] Upgrade Spring versions @haynescd 

# 2. Rollout
There are three PRs that we will all need to merge around the same time, still one pending:
- [x] [backend PR](https://github.com/cBioPortal/cbioportal/pull/10425)
- [ ] [cbioportal-docker-compose PR](https://github.com/cBioPortal/cbioportal-docker-compose/pull/23)
- [x] [frontend PR](https://github.com/cBioPortal/cbioportal-frontend/pull/4753) (mainly to fix localdb tests, note that this is not working yet)

# 3. Optional Tasks
## Configuration
- [x] Compile JSP files during the build, see: https://github.com/cBioPortal/cbioportal/issues/10382
- [x] Passing nested properties (related https://github.com/cBioPortal/cbioportal/issues/10352)
- [x] use `application.properties` instead of `portal.properties` @kalletlak 

## Docker Setup
- [ ] Improve image, see https://github.com/cBioPortal/cbioportal/issues/10376

## Clean Up
- [x] Remove old modules
- [ ] There is a TODO about dispatchservlets, what is this and do we need to do this? File a separate ticket if not essential?
    ```
    // TODO Consider creating separate DispatcherServlets as in the original web.xml
    // See: https://stackoverflow.com/a/30686733/11651683
    ```

**Comment by inodb** [comment]
Now that most of this is done and merged into the main branch I've created a separate PR with remaining work: https://github.com/cBioPortal/cbioportal/issues/10514
