### ISSUE TITLE
clean up database tables

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2054]
- [x] clean up production database leftover such as clinical_attribute
- [x] remove pdb data tables: pdb_uniprot_alignment, pdb_uniprot_residue_mapping #8749
- [x] remove rppa related tables: protein_array_* #8799 
- [x] remove other legacy tables: micor_rna, micro_rna_alteration, mutation_frequency, entity, entity_attribute, entity_link, patient_list, patient_list_list
- [x] sanger_cancer_census -  https://github.com/cBioPortal/cbioportal/issues/8895
- [x] uniprod_id_mapping - https://github.com/cBioPortal/cbioportal/issues/8868
- [x] pfam_graphics (once we MutationMapper tool is updated and crosscancer.do is retired. Are we using this data in OncoKB too?) (depends on text_cache) https://github.com/cBioPortal/cbioportal/issues/8917
- [x] text_cache if #6604 can be done (marked as low priority) https://github.com/cBioPortal/cbioportal/issues/8994
- [x] drug table if we decide to retire network #9095 
- [x] interaction once Network tab is removed #9191 
- [x] remove clinicalTrialKeywords from cancerTypes table #7661
- [x] remove `EXONIC_LENGTH` in `reference_genome_gene` #9257

**Comment by sheridancbio** [comment]
We should talk this week about this. It would be good to put together a concrete proposal for db changes by Monday so it can be reviewed next Wednesday 11am (Engineering Review Meeting)

**Comment by jjgao** [comment]
@sheridancbio can we do this soon? Happy to discuss in person.

**Comment by sheridancbio** [comment]
many tables were cleaned up during the transition to the 2.1.0 database schema.
For dropping pdb_uniprot_alignment I wonder if other centers have access to our externalized pdb services/database created by onur? Also, we hope to soon shift to using g2s instead, so maybe this should wait until then if other installers do not have the separate web service running for this info.
I'm not familiar with the protien_array_* tables. If these are unused I will make a PR to strip them from the db schema and portal code.

**Comment by jjgao** [comment]
pdb_uniprot_alignment and pdb_uniprot_residue_mapping are no longer used in the new code. We always point to the pdb services Onur created. Other centers also have access to our service. Anyone using the new code should be using that already.

protien_array_* tables can be just removed. That reminded me that the RPPA code should be clean up, eg. the RPPA related APIs in the doc should be removed -- they are not working any more.

**Comment by sandertan** [comment]
We might want to add `sanger_cancer_census` to this list.

**Comment by pieterlukasse** [comment]
and `pfam_graphics` ?

**Comment by jjgao** [comment]
@pieterlukasse yes.

**Comment by pieterlukasse** [comment]
@jjgao @sheridancbio I think this can be safely done now. In my last diagram I tried to identify all tables I think can be removed or "deprecated". Maybe @sheridancbio can review this? See https://raw.githubusercontent.com/cBioPortal/cbioportal/master/db-scripts/src/main/resources/cbioportal-er-diagram_v2.7.0.png

**Comment by jjgao** [comment]
@pieterlukasse @sheridancbio it'd be great to get this done.

**Comment by sheridancbio** [comment]
A card for this issue has been added to the backend pipelines backlog  cc: @n1zea144

**Comment by jjgao** [comment]
let's keep this open.

**Comment by jjgao** [comment]
let's keep this open.
