### ISSUE TITLE
new patient view issues

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#2269]
- [ ] the row heights of tables can be reduced a little. #2275
- [ ] the page is too wide for 13'' screen. In the current PV, the page the resizable based on the window size. Is there an easy to support that? #2276
- [ ] 'sort by cosmic' not working properly: http://www.cbioportal.org/beta/case.do#/patient?caseId=TCGA-3B-A9HP. #2277
- [ ] the first click on 'cohort' (mutations and cna tables) or 'cosmic' should order descendingly. #2278
- [ ] by default order by 'annotation for cna table' #2279
- [ ] match single hotspots to missense mutations only; and indel hotspots to inframe indels. #2280
- [ ] since we are paginating, we should make it super obvious that there are more data. #2281
- [ ] (this is probably for future) for the tables is it possible to use scroll instead of pagenation but still do lazy loading, ie. load when user scroll down. I saw many sites doing that nowadays. #2282

**Comment by JiaoJiao123** [comment]
- [ ] when I mouse over patient id, the Attribute and Value table displayed is not aligned. 
![screen shot 2017-03-31 at 2 56 58 pm](https://cloud.githubusercontent.com/assets/13951023/24565288/a66f69a0-1622-11e7-9bd8-a7975ef21208.png)

**Comment by jjgao** [comment]
@ecerami Agreed. Maybe we can create separate trello cards?

**Comment by jjgao** [comment]
@ecerami separate issues created.
