### ISSUE TITLE
Mutational Signature Support

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#4371]
Provide full-stack support for Mutational Signature (MS) data.

**Tasks for importing MS data into database:**

- [x] Extended [database schema](https://github.com/cBioPortal/cbioportal/blob/master/db-scripts/src/main/resources/cgds.sql) to capture MS metadata.
- [x] Create bean to represent an MS record in the context of importing ([model](https://github.com/cBioPortal/cbioportal/tree/master/core/src/main/java/org/mskcc/cbio/portal/model) package within core maven project).
- [x] Create Data Access Object for reading/writing MS metadata records. ([dao](https://github.com/cBioPortal/cbioportal/tree/master/core/src/main/java/org/mskcc/cbio/portal/dao) package within core maven project).
- [x] Create script for importing MS metadata into the database.
- [ ] Modify [ImportTabDelimData](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportTabDelimData.java) to support importing of MS data.

**Tasks for reading MS data out of database**
To be completed

**Task for proper integration of code**
To be completed

**Comment by jjgao** [comment]
@n1zea144 @dippindots is this issue still relevant?

**Comment by n1zea144** [comment]
No, I will close.
