### ISSUE TITLE
support custom groups within a study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5545]
This is for Part 1 for the [Cohort/Group Comparison project](https://docs.google.com/document/d/1gkHJ6LQYpM5eoT7ROjA8tChgG0kndaw3iyBqnlx0iPU/edit#).

A custom group contains a list of samples within a study or virtual study. 

- [x] define the data structure of a custom group #5541
- [x] support custom groups in session service #5542
- [x] add a new custom group #5543
- [x] custom group management #5544

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/2077
