### ISSUE TITLE
group/cohort comparison

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#5548]
This is for Part 2 for the [Cohort/Group Comparison project](https://docs.google.com/document/d/1gkHJ6LQYpM5eoT7ROjA8tChgG0kndaw3iyBqnlx0iPU/edit#).

Phase 1:
- [x] support custom groups within a study #5545
- [x] entry point to comparison page
  - [x] For custom groups: #5544
  - [x] For an existing attribute (pie chart) #5546
- [x] which store should be used to host the data for comparison page #5547 
- [x] define the input for the comparison page #5574
- [x] Comparison page framework #5551
- [x] Toggle groups to compare in comparison page #5579
- [x] Group Overlap tab (Venn diagram) #5552
- [x] Survival tab #5553
- [x] Mutations tab #5555
- [x] Copy-Number tab #5556
- [x] mRNA tab #5557
- [x] Protein tab #5558
- [x] Clinical Data tab #5554
- [x] Save comparison sessions into session service #5578
- [x] Make session service mandatory #5773

Future:
- [x] Using upset visualization in Overlap tab #5898
- [ ] Methylation tab
- [ ] Should we support continuous CNA data?
- [x] Alteration frequency plot? #5756
- [ ] Support patient level enrichments analysis #4637 
- [ ] treat overlapping part as a separate group #5803
- [ ] Integrate the Comparison component with Results page #5802
- [ ] Comparison tab in Results: allow group samples by gene/track #5804

**Comment by jjgao** [comment]
Once we have the Comparison page, we may want to rename the Enrichments tab in Results page to Comparison tab, which can include the Comparison subtabs to compare altered vs unaltered.

For Comparing without querying genes, we should go to the Comparison page.

**Comment by adamabeshouse** [comment]
** we need changes to enrichments API to handle multiple study input

**Comment by jjgao** [comment]
@alisman @adamabeshouse @kalletlak thanks for the great work!

Based on today's demo and discussion, I updated some of the issues and also assigned each to one or two of you. Please feel free to change assignments. Here is a quick summary of the remaining work. Please add if I missed anything.

- [ ] support multiple studies for Mutations and Copy Number tabs #5555, #5556
- [ ] modify the headers and url of comparison page according to #5551, #5579
- [ ] support post of groups of samples in comparison page #5574
- [ ] save comparison sessions into session service #5578 

- [ ] compare from a piechart #5546 
- [ ] support custom groups #5545

**Comment by jjgao** [comment]
created https://github.com/cBioPortal/cbioportal/issues/6250 for phase 2 and future work.
