### ISSUE TITLE
Group comparison - Phase 2

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6250]
- [ ] Methylation tab
- [ ] Should we support continuous CNA data?
- [ ] Support patient level enrichments analysis #4637 
- [ ] treat overlapping part as a separate group #5803
- [ ] Integrate the Comparison component with Results page #5802
- [ ] Comparison tab in Results: allow group samples by gene/track #5804
