### ISSUE TITLE
Switch to structure_variant table data for fusions

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6611]
# Backend
- [ ] remove fusions from the mutation_event table and leave existing fetch mutations endpoints un-touched.
- [x] add a new web service endpoint to pull fusions out from the new structural-variants table, e.g . `/structuralvariant-genes/fetch`
- [x] a new web API to fetch structural variants
- [x] a new web API to fetch structural variant enrichments
- [ ] cleanup unnecessary code(temporary code added to support fusions) once data is fixed

# Pipleline
- [ ] Import sv.txt
- [ ] Add documentation for importing structural variant data
- [ ] Are we still going to support fusions.txt?
- [ ] `show_profile_in_analysis_tab` is set to `false` for some of the fusion profile. should we write a migration script or update data files? -  temporarily fixed by patching in [code](https://github.com/cBioPortal/cbioportal/pull/7597/files#diff-ff2f05ea52f63fcd586a3c90ff15d64718e99a051a6f2b3944a4b8102e111c69R119)
- [ ] normalize profile names (e.g. for MSK-IMPACT they are just called Fusion. Which is not consistent with other profile names)

# Frontend
- [x] Study view: add a new fusion gene table
- [x] Patient view: add a new structural variants table https://github.com/cBioPortal/cbioportal/issues/7545
- [ ] add a new structural variant track to the existing plot on the patient view (?)https://github.com/cBioPortal/cbioportal/issues/7546
- [x] add sv/fusion profile option in query interface of single-study query https://github.com/cBioPortal/cbioportal/issues/1874
- [x] add sv/fusion profile option in query interface of multi-study query https://github.com/cbioportal/cbioportal/issues/7882
- [x] OncoPrinttab: switch to sv api https://github.com/cBioPortal/cbioportal/issues/6965
- [x] Cancer Types Summary tab: switch to sv api (hopefully it's already using oncoprint data) https://github.com/cBioPortal/cbioportal/issues/7798
- [x] Download tab https://github.com/cBioPortal/cbioportal/issues/7798
  - [x] switch to sv api for the table  (hopefully it's already using oncoprint data)
  - [x] add Fusions in the "Downloadable Data Files" section
- [x] Mutual Exclusivity tab: double check it works after switching
- [x] Plots tab(https://github.com/cBioPortal/cbioportal/issues/1879)
  - [x] add Fusion as a Data Type
  - [x] add Fusion as an option of "Style samples by"
- [ ] Mutations tab
  - [ ] Should we have SVs table? If so maybe we should have CNAs table as well? https://github.com/cBioPortal/cbioportal/issues/1877
  - [ ] More updates https://github.com/cBioPortal/cbioportal/issues/8092
- [x] Enrichments tab: add Structure Variants sub-tab (after Mutations) https://github.com/cBioPortal/cbioportal/issues/7832
- [x] Survival tab: double check the numbers are correct
- [x] Pathway (to be released): double check the numbers are correct

@khzhu @alisman @n1zea144

**Comment by khzhu** [comment]
use fetchStructuralVariantsUsingPOST to fetch only fusions then merge with mutations from fetchStructuralVariantsInMultipleMolecularProfilesUsingPOST in the frontend might be difficult since  return sets from two apis have complete different attributes? add a new endpoint to fetch structure variants might be easier. 
```
{
  "entrezGeneIds": [
   64759,9709
  ],
  "sampleMolecularIdentifiers": [
    {"molecularProfileId":"study_es_0_structural_variants","sampleId":"TCGA-A7-A13D-01"},{"molecularProfileId":"study_es_0_structural_variants","sampleId":"TCGA-BH-A0E6-01"}
  ]
}
```

**Comment by khzhu** [comment]
here is the development plan for using the new structural variants table:
# Backend:
- [ ] remove fusions from the mutation_event table and leave existing fetch mutations endpoints un-touched.
- [ ] add a new web service endpoint to pull fusions out from the new structural-variants table
e.g . /fusion-genes/fetch 
- [ ] a new web API getSampleCountInMultipleMolecularProfilesForFusions to collect fusion genes counts for the summary view
# Frontend
- [ ] add a new fusion gene table in the summary view
- [ ] add a new structural variants table in the patient view 
- [ ] add a new structural variant track to the existing plot on the patient view

**Comment by jjgao** [comment]
thanks, @khzhu! I update the to-do list in the description.

**Comment by jjgao** [comment]
It is a fairly big task. It would be a good idea to turn this into an epic and create separate issues for the tasks.

**Comment by khzhu** [comment]
thanks, @jjgao ! It is much clear now what I suppose to do. I will break down to a few sub tasks.
