### ISSUE TITLE
Adding arm-level CNA data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#6804]
Just wanted to capture the idea - this is not a priority.

- [ ] import the data as generic assay data https://github.com/cBioPortal/datahub/issues/1308
- [ ] (implement as part of discrete generic assay) add arm-level cna to OncoPrint (gain and hetloss should be displayed by default unlike gene-level cna), Plots, Enrichments, Download
- [ ] (implement as part of discrete generic assay?) add a new table "Arm-level CNAs" in study view.

future tasks:
- [ ] create another profile types `Arm-level copy number alteration` in query interface
- [ ] allow user to type `1p` or `1p:gain` or `1p:hetloss` in gene box for querying
- [ ] add arm-level CNAs to the CNA table in patient view?
- [ ] update documentation, including oql, faq, data format
- [ ] add to Cancer Types Summary tab when it's possible to query
- [ ]  add to Mutual Exclusivity tab when it's possible to query

@cBioPortal/product

**Comment by AndyBlake** [comment]
Second this - We end up loading it as sample data for all the arms which is perhaps less than ideal from a ui point of view.

**Comment by jjgao** [comment]
unstale

**Comment by AndyBlake** [comment]
Unstale

**Comment by dippindots** [comment]
Modified description:
- Checked finished items
- Move enrichments and study view new chart into `future tasks`

CC: @jjgao

**Comment by jjgao** [comment]
@dippindots I removed the items related to query arm-level cna data. I think the benefit may not justify the cost to implement that.

**Comment by dippindots** [comment]
@jjgao Thanks!
