### ISSUE TITLE
Improve Code Formatting Frontend (Prettier)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7034]
- [x] run prettier.js on all ts/tsx files in /packages AND /src
- [x] use a prettier ignore file to ignore generated files and any dist directories in packages and node_modules forders in packages if necessary
- [x] add a commit hook to run luke's prettier command (package.json scripts)
- [x] add a job in circleci to run prettier and fail if it detects problem (see genomenexus project for example of this (https://github.com/genome-nexus/genome-nexus-frontend/blob/master/.circleci/config.yml#L61-L67)
- [x] merge master branch with prettier applied to rc
- [x] indicate how to fix old open PRs when `prettierFixLocal` script is missing (see description here: https://github.com/cBioPortal/cbioportal-frontend/pull/3016)
