### ISSUE TITLE
visualize single cell data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7041]
One option would be implement the single cell data as a separate resource (database, api, web) and i-frame it into patient view.

- [x] identify a single cell dataset, ideally together with bulk sequencing data (#7153)
- [ ] define signal cell data format (htan)
- [ ] design database scheme (Q: should we set up a separate databbase?)
- [ ] api
- [ ] visualization
  - [ ] tsne / umap
  - [ ] switch genes for rendering
- [ ] include visualization in patient view tab.

Two alternative strategies to implement this

1. From scratch

Create a scatter plot with functionality to change coloring using dropdown

2. Use existing app

Use spectrum (https://spectrum.mskcc.org/scrna/) & github repo https://github.com/shahcompbio/mira-react. This uses React as well so we could potentially also only use the frontend layer. Note however that this uses some binning for the charts and not dots

References:

- Understanding tSNE: https://distill.pub/2016/misread-tsne/

Other single cell visualizations:

- Broad Single Portal https://singlecell.broadinstitute.org/single_cell/study/SCP1/-single-nucleus-rna-seq-of-cell-diversity-in-the-adult-mouse-hippocampus-snuc-seq#study-visualize

**Comment by ecerami** [comment]
Before we roll our own, I think we should start by first assessing existing options, to determine if 1) we can just use an existing framework;  and/or 2) borrow ideas.  We actually don't have a whole lot of time if we want to go live with something for HTAN in July/August;  so, timeline considerations are important.

**Comment by jjgao** [comment]
@ecerami agreed. We should go with existing open source solutions if possible.

**Comment by schultzn** [comment]
Just keep in mind that the proposed first product is a scatter plot visualization of TSne data with color coded dots based on cel attributes. That is pretty simple and probably does not require us to borrow existing code, or am I missing something?

Niki.

**Comment by inodb** [comment]
maybe silly question: are we just doing RNA visualization?

I do think it might be good to consider borrowing code for even a simple tSNE plot, because of the questions around how the data should be served. Would like to avoid starting our own idiosyncratic data format of storing single cell information to support that one plot. A very simple solution is to use the file attachments and stick a PDF in. If there are good existing tools for doing tSNE etc we can do an iframe. Then we don't even have to worry about coming up with some data schema ourselves. We would import the data into that tool. For both those cases I think then it's more a matter of extending cBioPortal to make it easy for people to find the cases with single cell data by adding some sample clinical attributes:

- have some way to find patients with single cell data
- find samples with certain cell composition

cBioPortal is then the layer that allows you to do patient/group comparison on those high level attributes and people can use whatever single cell tool is popular to drill down further inside some iframe.
