### ISSUE TITLE
sample selection based on treatment timeline data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7042]
It would be very useful to be able to select samples after a patient is treated with a certain treatment (post- or on-treatment). This will be the first feature that allows sample/cohort selection based on longitudinal data. It will allow us to select a cohort like "stage iv lung cancer patients with EGFR T790M mutation in the sample after treated with Erlotinib".

- [x] Selection json format
- [x] API
- [x] Study view: a table of "Treatments" with the following columns: `Treated with`, `#`, `Freq`. (Not sure how useful is Freq)
- [x] Finish the RFC
- [x] Build Initial prototype

RFC: https://docs.google.com/document/d/1-3huFLgugRh8V6omDN3ycNebPrfCbTS71AuAY1Npr30/edit
