### ISSUE TITLE
Patient View File Attachments

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7054]
Enable importing attachments on the patient view to support PDFs and IFrames.

The attachments should be linked to:

- Patients
- Samples

Ideally we can also link to:

- Study https://github.com/cBioPortal/cbioportal/issues/7045

TODO:

- [x] Design API: https://github.com/cbioportal/cbioportal/issues/7003
- [x] Potential backend implementation of API, depending on design choices for #7003 
- [x] Frontend part to show files/iframes in patient view: https://github.com/cBioPortal/cbioportal-frontend/pull/3019
