### ISSUE TITLE
Mutational Signatures

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7057]
As the phase one of the mutational signatures work, we want to make mutational signatures data available on the following places:
- (Result View Page) oncoprint tab (a heatmap track per signature)
- (Result View Page) plots tab
- (Result View Page) download tab
- (Patient View Page) a new mutational signatures tab

The remaining tasks:
- [x] Update mutational signatures data (V3) and data converter: https://github.com/cbioportal/cbioportal/issues/7198
- [x] Using new codes to generate signatures to be imported into cbioportal: https://github.com/cBioPortal/cbioportal/issues/7888
- [x] dockerize the process from any MAF to final cbioportal file: https://github.com/cBioPortal/cbioportal/issues/7889
- [x] Finalize the implementation for mutational signatures tab on Patient View Page: https://github.com/cBioPortal/cbioportal/issues/7804

**Comment by jjgao** [comment]
let's keep this open until we release the feature.
