### ISSUE TITLE
Timeline enhancements for GENIE's PRISSMM format

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7066]
Visual:

- [x] Add sample type to tooltip for sample acquisition and sequencing date
- [x] Show the drugs before assessments? 
- [x] Imaging assessment (add word “assessment”)
- [x] Deal with stacking of dots in sample place
- [x] Stacking timeline events enhancements (#7849)
- [ ] Order: PATH (status, then site), Imaging (status, then change), MedOnc (status, then change)
- [ ] Figure out how we want to show death event. Proposed is a black square. We currently add a black dot in Status based on OS_MONTHS. (Note that this also requires a migration: https://github.com/cBioPortal/datahub/issues/1262)
- [ ] How do we determine sample labeling (1/2/3) for patient with multiple samples. In GENIE-DFCI-007313, sample 3 was acquired before 2. Should order of sample acquisition be more important than order of sequencing? See GENIE-DFCI-008031
- [x] What is going on in GENIE-DFCI-008085 - Samples with black dots in timeline but no number, just "-". "Error. Cannot find data for sample" (Fixed: but note sample acquisition is missing for one sample in data)
- [ ] Can we find a way to break the time axis when showing prior diagnoses in the past, example: GENIE-DFCI-036820, GENIE-DFCI-051244

Visual and need data:

- [ ] Color drugs by family, then different shades of that color if multiple different drugs of the 
    same category were used. Six proposed families / colors: (Immunotherapy, Cytotoxic, intravenous therapy, Cytotoxic oral therapy, Hormonal therapy, Other (vaccines, CART, etc.), Investigational (black)) (Not sure if this is feasible given that we don't have the data, maybe we can color by regiment instead?)
- [ ] Split Status (Cancer present) from Status Change. No cancer = empty circle. Cancer = black circle. Indeterminate = grey
- [ ] Change Status Change colors slightly (in separate row - Is only shown when cancer is present). Worsening = Red. Improving = Green. Stable = Yellow. Indeterminate = faded half red half green … or grey. Mixed = half red / half green

For timeline 2.0 (the new refactored React based timeline):

- [x] Expand/collapse functionality (this exists in current clinical timeline lib but not enabled) (https://github.com/cBioPortal/cbioportal/issues/6953)
- [x] Add zoom to timeline
- [x] Add biomarkers later (PSA, etc.) - maybe expand more compact row to taller chart
- [x] Increase spacing slightly between categories  ("tracks")
- [x] Somehow connect row item to row name on hover? Or always show a line? (this exists in current timeline lib but it doesn't work very well)
- [ ] Support DOB (date of birth) as time of 0. Display years in START_DATE and STOP_DATE; display RANGE in STOP_DATE

Data related:
- [ ] Add diagnosis date(s) to timeline. Not sure if this is already in data
- [ ] Add metastatic events. Need to figure out how this is represented in data and show accordingly (PENDING DATA)
- [ ] Add PRISSMM P (Pathology) (highest accuracy, lowest error rate)
    *   PATH Status: Did any specimen in a report show cancer? Show status just as described above (present absent indeterminant premalignant)
        *   Exception: premalignant disease (dark grey?)
        *   Link the specimen to sequenced sample with number
    *   PATH SITE: Second row for primary vs metastatic disease, color code primary vs met
        *   Filled vs not filled if there was cancer vs not

The above list was created from: https://docs.google.com/document/d/14__bVskxb27bp1uObue43_jYcT8qv7KmOhjunLPbaYQ/edit. There are more data requirements in that document

Current example:

https://genie-private.cbioportal.org/patient?studyId=nsclc_genie_bpc&caseId=GENIE-DFCI-000036

**Comment by jjgao** [comment]
We should prioritize this one.

**Comment by jjgao** [comment]
added this epic to #7520.

**Comment by alisman** [comment]
@schultzn @inodb is the following track ordering what we want?

![image](https://user-images.githubusercontent.com/186521/86653385-250ece80-bfb3-11ea-8029-d378512b5cce.png)

**Comment by schultzn** [comment]
This looks mostly good.

But the regimens are not resolved properly. Multiple drugs as given as part of a regimen (Cancer-Directed Drug 1 + Cancer-Directed Drug 2, etc.) should appear together in the timeline. 

Let me know if you have any questions about this.

**Comment by alisman** [comment]
@schultzn  just to confirm, this it should like it does in old timeline (bottom):
![image](https://user-images.githubusercontent.com/186521/86945220-cf533700-c116-11ea-94d3-c80671181890.png)

**Comment by schultzn** [comment]
We should plan this carefully. 

Drugs should be ordered in the same they were in the old timeline. And drugs given as a regimen should appear together, with drug 1 listed first, etc.

We can think about other ways to visually indicate that the drugs belong together, but that is optional.

N

**Comment by inodb** [comment]
let's confirm if all of these are solved
