### ISSUE TITLE
Support for login with Synapse

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7154]
TODO:

- [x] Set up KeyCloak on Kubernetes (https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/49)
- [x] Figure out how to use it to authenticate on Synapse

**Comment by inodb** [comment]
@n1zea144 created an epic for this, since we need it for both GENIE and HTAN. Let me know if you already had some other issue to track this. Thanks!

**Comment by n1zea144** [comment]
I would say this card is 95% done.  The infrastructure has been put together to support Keycloak / SAGE integration.  What we need to do now (besides setting up an HTAN cBioPortal) is configure HTAN specific Keycloak configuration - 

- [ ] Setup Keycloak configuration  - user list
- [ ] Setup Keycloak configuration - roles
- [ ] Setup Keycloak configuration - custom login page

**Comment by inodb** [comment]
still a few things left for this one

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio any update on this?
