### ISSUE TITLE
Public Release of API

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7258]
Before the official 1.0 release of the API we should do the following:

- [x] Create User Friendly API Documentation. Current API auto generated docs are not easy to read. Give general overview of API (#7469)
- [x] Deprecation message (https://github.com/cBioPortal/cbioportal/issues/2967)
- [x] Go over all API endpoints and check consistency
    - [ ] In particular generic assay endpoints: https://github.com/cBioPortal/cbioportal/issues/6955
- [ ] Address issues identified while going over all endpoints: https://docs.google.com/document/d/1KC07Rl_oD6jYUyYahv4UrS-GIuLWnr4biaWop826U1Y
- [ ] Only use public API endpoints (https://github.com/cBioPortal/cbioportal/issues/3289)
- [ ] Jupyter Notebooks
    - [ ] Python (can use a lot from https://github.com/mskcc/cbsp-hackathon)
    - [ ] R (Deprecate cgdsr in favor of cBioPortalData and rapiclient if endpoint is not supported)
- [ ] Document other clients
    - [ ] JavaScript (fix https://github.com/cBioPortal/cbioportal/issues/6716)
    - [ ] Java
- [x] Remove A/B/C etc from endpoint names (find another way to sort endpoints)
- [ ] Styling/navigation of API page. Should it live inside docs.cbioportal.org and/or inside cBioPortal shell, or should we expand swagger page with more custom look (related: https://github.com/cBioPortal/cbioportal/issues/2969)

For auth enabled portals:

- [ ] For each of the client docs include how to connect to an authenticated portal. It would be good to merge https://github.com/cBioPortal/cbioportal/pull/6999, so tokens are supported with keycloak.

Would be nice:

- [ ] Remove Category from Sample List API (https://github.com/cBioPortal/cbioportal/issues/4933)
