### ISSUE TITLE
Support many survival types

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7292]
There are two challenges:

- Currently, we don't have a way to encode the survival events as meta data, e.g. deceased for os, progressed for pfs, so they are hard-coded. We need to find a solution for that? Can we use 0 & 1 and describe them in attribute description?
- We need a better way to show the plots when there are many different types - see @schultzn's comments below.

Tasks:
- [x] Frontend - support other types of survival plots (other than OS and DFS)
- [x] Investigation: find all vocabulary for existing survival types
- [x] Database - Migrate current survival data and meta data
- [x] Pipeline - Modify importer to convert the current data to 0/1
- [x] Pipeline - Write a tool to migrate files 
- [x] Frontend - support 0/1
- [x] Curation - Migrate the files with the tool @cBioPortal/curation  
- [x] Curation - Manually double check files including meta files @cBioPortal/curation 

===
FYI - from [comment here](https://github.com/cBioPortal/cbioportal-frontend/pull/3099#issuecomment-597835288)

"For AACR Project GENIE, we can expect dozens of different outcome measures for each study, so having them all show up in the current format might be tricky. Maybe we can show them in a pull down menu once there are >= 10 outcome measures? These could be prioritized by the outcome measures for which more data are available (as we start showing outcome for specific therapies. the data will get sparse and there may be only a few patients with outcome information), similar to what we are already doing in other places for the availability of clinical attributes (OncoPrint, study view)."

**Comment by schultzn** [comment]
Yes, 0 and 1 are good. Can we allow so exceptions to support the existing data, e.g. DECEASED and LIVING? Or would that complicate things in virtual cohorts?

**Comment by jjgao** [comment]
@schultzn I think we should convert all data to 0/1 if we decide to do that. We can easily migrate the current database and also put some code to convert the data when importing.

@n1zea144 @ritikakundra thoughts?

**Comment by jjgao** [comment]
- [ ] Frontend - support 0/1
- [ ] Database - Migrate current survival data and meta data
- [ ] Pipeline - Modify importer to convert the current data to 0/1
- [ ] Pipeline - Write a tool to migrate files 
- [ ] Curation - Migrate the files with the tool @cBioPortal/curation  
- [ ] Curation - Manually double check files including meta files @cBioPortal/curation

**Comment by dippindots** [comment]
Currently, I am mapping the `DECEASED` to `1` for overall survival status, is that correct? I saw some comment in the codebase: `os: DECEASED-->1, LIVING-->0; dfs: Recurred/Progressed --> 1, Disease Free-->0`

**Comment by ritikakundra** [comment]
@jjgao changing OS and DFS to 0/1 should be easy. But other attributes like PFS, RFS,DSS etc might be tricky to update

**Comment by dippindots** [comment]
@ritikakundra Could you elaborate more, currently, I am trying to follow this pattern to change the data:
    OS: `DECEASED-->1, OTHER-->0`
    PFS:`CENSORED-->1, OTHER-->0`
    DFS: `Recurred/Progressed-->1, Recurred-->1, OTHER-->0`
    DSS: `DEAD WITH TUMOR-->1, OTHER-->0`
    EFS: `Censored-->1, OTHER-->0`

**Comment by jjgao** [comment]
@dippindots could you get the complete vocabulary from public portal for all these _status?

**Comment by dippindots** [comment]
@jjgao @ritikakundra From my observation and @leexgh 's frontend implementation, here is the whole vocabulary:

OS: `DECEASED`  (e.g. study: `acc_tcga`)
DFS: `Recurred/Progressed` or  `Recurred` (e.g. study: `acc_tcga`)
PFS:`CENSORED` (e.g. study: `acc_tcga_pan_can_atlas_2018`)
DSS: `DEAD WITH TUMOR` (e.g. study: `acc_tcga_pan_can_atlas_2018 `)
EFS: `Censored` (e.g. study: `nbl_broad_2013`)
PF: `Progressed` (e.g. study: `nbl_amc_2012`)
PLATINUM_OS: `1` (e.g. study: `egc_msk_2017 `)
PLATINUM_PFS: `1` (e.g. study: `egc_msk_2017 `)

**Comment by ritikakundra** [comment]
@dippindots: For OS, the vocab is LIVING and DECEASED
DFS: Recurred/Progressed and DiseaseFree

For rest, we don't have a fixed vocab and could vary study to study.

**Comment by jjgao** [comment]
@dippindots could you pull the complete vocab (e.g. LIVING and DECEASED) based on the data in  the portal.

**Comment by dippindots** [comment]
Sure! @jjgao
OS: `DECEASED` and `LIVING ` (e.g. study: `acc_tcga`)
DFS: `Recurred/Progressed` or  `Recurred` and `DiseaseFree` (e.g. study: `acc_tcga`)
PFS:`CENSORED` and `PROGRESSION` (e.g. study: `acc_tcga_pan_can_atlas_2018`)
DSS: `DEAD WITH TUMOR` and `ALIVE OR DEAD TUMOR FREE` (e.g. study: `acc_tcga_pan_can_atlas_2018 `)
EFS: `Censored` and `Event` (e.g. study: `cscc_hgsc_bcm_2014`)
PF: `Progressed` and `Progression free` (e.g. study: `nbl_amc_2012`)
PLATINUM_OS: `1` and `0` (e.g. study: `egc_msk_2017 `)
PLATINUM_PFS: `1` and `0` (e.g. study: `egc_msk_2017 `)

**Comment by jjgao** [comment]
Thanks,  @dippindots . for EFS, I think Event should map to 1 and Censored to 0. For PFS, Progression to 1 and Censored to 0. Others look good.

**Comment by n1zea144** [comment]
@dippindots @ritikakundra @jjgao I realize this PR is centered around the public portal, but I thought I would mention that when part of the [migration script](https://github.com/cBioPortal/cbioportal/blob/765a1ee68d84ae3abb0ad6f5837494b7d08bceef/db-scripts/src/main/resources/migration.sql#L858) is run against the private database, additional attributes are identified beyond what is captured here (see below).

Are there plans to run the migration script on all data within the private database?  If so, we should do an audit of the data to make sure that all values are compliant with the script.

* bfci
* drfs
* idfs
* loco_reg
* brain_recur
* dor

![image](https://user-images.githubusercontent.com/366003/80534756-c2bf9f00-896d-11ea-8d13-769e272e1b5d.png)

**Comment by dippindots** [comment]
@n1zea144 Some comments above are outdated, in this [pr: 7328](https://github.com/cBioPortal/cbioportal/pull/7328), I am using the vocabularies captured in this [issue: 7322](https://github.com/cBioPortal/cbioportal/issues/7322) which captured the vocabularies from both public database and private database.
