### ISSUE TITLE
Support transcript switch on result view

### ISSUE THREAD

**Issue by leexgh** [cBioPortal/cbioportal#7479]
Have a transcript dropdown next to the lollipop
![image](https://user-images.githubusercontent.com/16869603/87187018-7c19e980-c2ba-11ea-80a4-37d23e86a6f3.png)

### New design
**Enabling transcript dropdown:**
- [x] query one gene per time instead of query all genes at once
- [x] figure out why mutations are missing if transcript dropdown is enabled
Update: 
Mutation mapper can't handle chromosome 23 and 24, so it causes missing mutations when transcript dropdown is enabled. This issue is fixed in https://github.com/cBioPortal/cbioportal/issues/7504
- [x] add a flag to enable or disable transcript dropdown 

**Mutation table**
- [x] always show fusions
- [x] canonical transcript always uses data from database, non-canonical uses data from GN
- [x] only show mutations belongs to the selected transcript(might need to filter out some mutations) plus `Fusion`
- [x] make sure `Protein Change` and `Mutation Type` are updated at the same time
- [x] update hgvsc column
- [x] If the mutation is categorized as `Other`, show original data in Mutation Type column

**Mutation mapper**

- [x] make sure filter function on mutation count panel works
- [x] split out `Other` to `Other` and ` Fusion`

**Adding selection to urlWrapper**
- [x] adding gene to urlWrapper
- [x] adding transcript id to urlWrapper

TODO
- [x] Fixing protein change with `*` (like `* 280 *`)
- [x] backend PR to add enable_transcript_dropdown to config file

**Comment by leexgh** [comment]
@jjgao @inodb @onursumer As we discussed, if the protein change differs in database and genome nexus, on the first load which is the first time we go to results view page, we show protein change from database. On the second load which is when we switch to another transcript and switch back, we also show it from database but with a warning icon next to it. 

We also have a logic in the code to filter mutations without protein change result (see logic [here](https://github.com/cBioPortal/cbioportal-frontend/blob/master/packages/cbioportal-utils/src/mutation/MutationAnnotator.ts#L132-L133)). So I think we intend to remove those mutations. Here is the question, If database has protein change while genome nexus doesn't, should we remove this mutation? Or we should show it for the first load and remove it for second?

Besides this, personally I think this first load and second load setting is confused to me, if I'm a user I might prefer things to be consistent no matter how many times I visit it. So I'm thinking maybe we can add a switch or checkbox to let users select whether showing warning or whether do the filter? Do you have any suggestions?

**Comment by leexgh** [comment]
@jjgao @alisman @inodb @onursumer adding transcript id to urlWrapper is tricky, we have to change `activeTranscript` to MobxPromise, some concerns I have:
1. we use `activeTranscript` in tons of places in mutation mapper, although I fixed all the ts errors, I'm not sure if it has some further impact
2. we have to update an observable value(setSelectedTranscript) in a computed component(geneTabContent), and that will cause a mobx error, we need to have some reaction to handling this, but I feel it's not a good way to do this

do you think it's worth to add transcript id to urlWrapper? I'm thinking maybe having gene in the url is enough?

**Comment by jjgao** [comment]
@leexgh I think it would be good to include the transcript id in the URL if the user changes it.
