### ISSUE TITLE
cBioPortal Home Page "Installation Map"

### ISSUE THREAD

**Issue by n1zea144** [cBioPortal/cbioportal#7491]
We would like to have a Google/Google-like map on the homepage which features cBioPortal installations throughout the world.  A visitor to cbioportal.org can choose to register their installation by interacting with the appropriate UI element to access a form to capture relevant information about their installation.

A prototype of this feature was built in a prior cBioPortal hackathon which utilized Google maps, [forms](https://docs.google.com/forms/d/1j1IBeNjwi5ZpWNchxnb9SdbBkdh1W785uAlza_Wsl7U/edit) and fusion.  Sometime after the hackathon, the fusion web service was decommissioned.

If Google forms and maps are continued to be used, a new spreadsheet parser / transfer tools will probably need to be developed.  Some other storage mechanism may be needed to serve data to the frontend as the map api does not support persistence.  That is, to render the map, the browser would need to obtain a javascript data file containing the points to plot, and then upload it to google in order to request an output map.  Also, the dynamic map API seemed too expensive, but the static API map was not scrollable and maybe did not scale to show the whole world in a way that was satisfactory without zooming (which is not provided).

Since the Google based prototype is no longer viable and Google maps may be cost prohibitive, its recommended to look for an alternative mapping technology.

- [ ] adding an installation map in the frontpage (right side bar?), including the location and institution based on the [survey result](https://docs.google.com/spreadsheets/d/1CNgDpRL3u7pP2LEzSKpdHPoJwayYQ_g2URS-oDizEo4/edit#gid=1230199906)
- [ ] link to the map so that users can open the map in new tab - something like [this map](https://www.google.com/maps/@42.3604082,2.7477721,5.97z/data=!4m2!6m1!1s1IV36HethEDzptj4uhGK66QPpw_I8nJ6A)
- [ ] link to the [survey](https://docs.google.com/forms/d/e/1FAIpQLSflQdN956q7Xh5caO8z8jIaF6uMLBkKrSxFvPi8OhNBWB247w/viewform)
- [ ]  update the map automatically when new entry is enters
  - should we moderate in order to avoid spams?
- [ ] investigate if Google Maps API is affordable

**Comment by inodb** [comment]
Might be a good project for @Luke-Sikina's intern. Need to spec out further

**Comment by jjgao** [comment]
@n1zea144 @sheridancbio I updated the description with a to-do list.
