### ISSUE TITLE
Rebuild patient page clinical timeline using React

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal#7520]
- [x] handle zoom and trimming
- [x] Reproduce color/shape/size options of data points
- [x] Implement export to formats
- [x] Improve handling of mult-event days
- [x] Handle nesting track groups
- [ ] Expand collapse track groups
- [x] Write unit tests
- [x] Handle browser resize
- [x] Tooltip dates should be in format x years, y months, z days
- [x] add config to enable/disable new timeline, so we can release it to genie-private portals w/o affecting public/mskcc portals. Maybe some property like: `feature_flags.show_react_timeline`?
- [x] Tooltip gets cut off on the right end of the timeline (try e.g. https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P01)
    <img width="150" alt="Screen Shot 2020-08-12 at 11 16 12 AM" src="https://user-images.githubusercontent.com/1334004/90050278-f9fb5700-dca3-11ea-9756-670f347552b9.png">
- [x] The old timeline allowed one to keep a tooltip open when you click on it (like pin it). Can we re-enable that feature in the new timeline?

PRISSMM Enhancements list
https://github.com/cBioPortal/cbioportal/issues/7066

For future work:

- show multiple tooltips with vertical cursorbar
