### ISSUE TITLE
Adding expression data from normal samples

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7528]
RFC document: https://docs.google.com/document/d/1YdS3b3qJLHXnsS84qjDWlfWPCClLP9bhxA7mj5xXhv4
Frontend:
- [ ] Expression tab
- [ ] Plots tab
- [x] z-scores using normals as reference

Backend:
- [ ] API to pull normal expression?

Pipeline:
- [x] Calculating z-scores based normals as reference
- [ ] Should z-scores be imported as a separate profile?

Curation:
- [ ] What data are available? Is it possible to do it for Pancaner Atlas?

**Comment by alisman** [comment]
@jjgao @inodb is this still desirable/viable?
