### ISSUE TITLE
Testing authenticated portals

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7584]
### App
- [ ] Check whether all private portals are running (triage missing it seems)
- [ ] Run a set of e2e tests against a private portal

### API
- [ ] Use token and confirm response contents
- [ ] Use token and confirm response times

### Login
- [ ] Test login with google @alisman (public & GENIE)
- [ ] Test login with microsoft @alisman (public & GENIE)
- [ ] Test login for MSKCC NetIQ (there might be a service account)
- [ ] Test login for SAML
- [ ] Test login with keycloak?

### App
- [ ] Spin up an authenticated portal with e2e tests

### API
- [ ]  Use token and confirm response contents
- [ ] Use token and confirm response times

### Spring security
- [ ] test startup for various authenticators @n1zea144 @inodb @pvannierop
