### ISSUE TITLE
Improving generic assay features

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7658]
- [x] generic assay in download tab #7363
- [x] improve the generic assay query interface in OncoPrint tab #7656
- [x] add generic assay data to Comparison page #7654

**Comment by dippindots** [comment]
Moving the future work to Improving generic assay features phase 2 https://github.com/cBioPortal/cbioportal/issues/7964.
