### ISSUE TITLE
improve support of custom data

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/cbioportal#7728]
Custom data can be added on the study view through the menu `Charts` -> `Custom Data`. There are a few limitations of the current implementation:
- Only categorical data is supported (it was originally meant for defining custom groups of samples (before the custom groups functionality); Numerical data is not supported
- The custom data is not saved to the user profile unless the data is displayed a chart
- Sharing of the data to other users is not supported

![image](https://user-images.githubusercontent.com/840895/88483868-ae714b00-cf38-11ea-8cc9-f098413e578c.png)

Here is a list of improvements:

- [ ] Support both categorical and numerical data #7724 
  - We can/should use the same format for clinical data in [OncoPrinter](https://www.cbioportal.org/oncoprinter)
- [ ] Save the custom uploaded data to the patient profile (sessions service), similar to custom groups #7726
- [ ] Allow user to show/hide a custom attribute as a chart, and delete a custom chart #6482 
- [ ] Allow sharing custom attributes (similar to sharing custom groups) #7609 
- [ ] Make the custom data available in Results view #7619
