### ISSUE TITLE
GENIE BPC post release bugs list

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7876]
https://genie-private.cbioportal.org/study/summary?id=nsclc_genie_bpc

Study view fixes:

- [ ] Sample Treatments and Patient Treatments should show up by default - instead they show up with 0.1% data availability in the Charts Menu
- [ ] The "Other cancer" charts still seem off: we are missing data for 71.3% of samples
- [ ] We could rename two charts:
   - [ ] GENIE Sequence Year - rename to "Year of sequencing"
   - [ ] "Is the patient dead at time of curation" (YES/NO) should be changed to "Patient vital status at time of curation" (ALIVE/DECEASED)

Timeline data questions:

- [ ] In GENIE-DFCI-011116, why is there a 1 month delay between sample acquisition and sequencing, but the therapy (use of erlotinib for EGFR L858R, use of osimertinib for EGFR T790M) starts right after sample acquisition and seems to anticipate the sequencing result? Similarly for GENIE-DFCI-011355
- [ ] GENIE-DFCI-015198 has two distinct lung cancers, >5 years apart. Same for GENIE-MSK-P-0002996. In each case, one is the index cancer, the other isn't. We really need to introduce a new level between patient and sample for cancer incidence

Timeline fixes here: https://github.com/cBioPortal/cbioportal/issues/7066

**Comment by inodb** [comment]
@alisman sorry i just moved that bit to the timeline prissmm enhancements epic. But agree order sequentially by top track makes sense. So yes order by collection date first

**Comment by jjgao** [comment]
@inodb do we need to reopen this?
