### ISSUE TITLE
GENIE BPC Study View Treatment Selection Enhancements

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7877]
- [x] Compare from the table component on the study view (https://github.com/cBioPortal/cbioportal/issues/7831)
- [x] Sometimes the search field is hidden behind a chart below it (I grayed out the counts and drug names)
   <img width="411" alt="Screen Shot 2020-09-11 at 11 18 51 AM" src="https://user-images.githubusercontent.com/1334004/92943432-bfaae400-f420-11ea-9a9d-08c4c01c7050.png">
- [x] Show the treatment selection charts higher up by default (they're often hidden at the bottom)
