### ISSUE TITLE
GENIE BPC Survival Outcome Improvements

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#7878]
See: https://genie-private.cbioportal.org/study/summary?id=nsclc_genie_bpc

- [x] Comparison page show p-values (https://github.com/cBioPortal/cbioportal/issues/7805)
- [x] Hide some charts on the study view 
  - [x] https://github.com/cBioPortal/cbioportal/issues/7830 
  - [x] https://github.com/cBioPortal/datahub/issues/1266
  - [x] https://github.com/cBioPortal/cbioportal/issues/7915

**Comment by dippindots** [comment]
@inodb should we close this epic? All related tickets closed.
