### ISSUE TITLE
Improve Docker Compose Setup

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8045]
We could make some more changes to improve the docker compose setup: https://github.com/cBioPortal/cbioportal-docker-compose

- [ ] Try to get rid of all error messages in the logs that show up when following instructions
- [ ] Create a clean up script. There seems to be some problem with rerunning the instructions `./init.sh` and `docker-compose up` (the database won't properly migrate)
- [ ] For non-docker based install docs be more explicit that we recommend to use the docker based installation

**Comment by cannin** [comment]
Please address this issue #7972 in this work.
