### ISSUE TITLE
MSK EKS Properties Configuration

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#8951]
- [ ] Darwin integration does not seem to be working (it doesn't show the ddp logo in the header of the patient view)
- [ ] survey banner doesn't work atm, but should work once rolled out
- [x] OncoKB does not seem to work with the internal dashi endpoint. Only with currently public data
- [x] API tokens don't seem to be working (at least for me)

Can test here https://msk.cbioportal.aws.mskcc.org/
