### ISSUE TITLE
set up single cell server for cptac data

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9246]
- [x] set up AWS EC2 Node
- [x] add ssl certificate
- [x] add custom tab config to test environment
- [x] solve issue with "Callback for tab x not found"

Remaining issues before releasing to production:

- [x] cellxgene only shows one patient. ~Maybe we disable it for now and only have vitessce?~ Maybe we show it just for that one patient
- [x] On Results Page. Idea was that one could explore the combined set of patients and e.g. show expression of the queried gene. Right now only single patient is shown. Maybe disable as well for now?
- [x] It would be nice to import the derived values from the single cell data as generic assay data as part of roll out of this feature. Jessica has already curated it. Datahub PR pending. 
- [x] On the study view it is not possible to select cases that have single cell data. It looks like the curated generic assay data already supports this
- [x] Right now the tab shows up everywhere. Also for cases that have no single cell data: https://beta.cbioportal.org/patient?studyId=ucec_tcga_pub&caseId=TCGA-BK-A0CC. Either we'll need to implement https://github.com/cBioPortal/cbioportal/issues/9200. Alternatively I'm wondering if embedding it as an iframe using resource data might work?
- [ ] Let's show two bar charts, rather than the left one being a lollipop like chart on patient view
- [x] Indicate on the tab that it's beta, maybe just `Single Cell Data (beta)`
- [ ] There is a reference to a specific domain of cBioPortal rather than the location the plugin is mounted at (it's hardcoded to beta.cbioportal.org):
    ```
    Access to XMLHttpRequest at 'https://single-cell.cbioportal.org//singlecelldata/studies/gbm_cptac_2021/C3L-02705/meta.json' from origin 'https://master.cbioportal.org' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://beta.cbioportal.org' that is not equal to the supplied origin.
   ```

Other data issues required to be fixed before production release:

- [x] Plots tab not working: https://bit.ly/35a95le. Seems like a data issue
- [x] C3N-02769 says it has a fraction of 0 epithelial cells, but in vitessce I see a couple
- [ ] 01816 case is a BRAF mutated case, which supposedly has many epithelial cells in the cell type fractions, but there are no epithelial cells in vitessce
- [x] the generic assay says it is a fraction of cells, but the values seem to be cell counts rather than fractions

Longer term thoughts:

- If we curate the data for cellxgene team we could maybe get around having to manage the viewer ourselves
- Some way to combine multiple datasets for the results view page would be great, but not sure how feasible. Maybe worth discussing with vitessce/cellxgene teams
- It might make sense to make this part of the main codebase rather than a custom tab over time
