### ISSUE TITLE
Release 4.0.0

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal#9308]
Migrations:

- [ ] Include database cleanup work
- [ ] Increase size of field STABLE_ID in genetic_entity table
- [ ] SV format changes
