### ISSUE TITLE
API endpoint outstanding issues

### ISSUE THREAD

**Issue by jagnathan** [cBioPortal/cbioportal#9342]
List of issues

https://docs.google.com/document/d/1KC07Rl_oD6jYUyYahv4UrS-GIuLWnr4biaWop826U1Y

- [x] Move InfoController to Public
- [x] Move STRUCTURAL VARIANTS to Internal
- [ ] ~Move StudyView to Public - 14 end points~ (Can be done in a next version)
- [x] Generic Assays Data ? There are only 3 endpoints in this controller. which end points to move to separate controller? Data and Meta separated.
- [x] Generic Assay - GET endpoints & Tests #9433 
- [ ] ~Generic Assay Documentation #7647~ (Separate epic created #9439)
- [x] Gene Panels - 5 endpoints. Is it required to move "data related" end points to a separate controller? #4225 https://github.com/cBioPortal/icebox/issues/177
- [x] Ordering of controllers in Swagger
- [ ] Look at openAPI upgrade (should be a ticket already) #6750

**Comment by jagnathan** [comment]
URL for Get Request for Generic Assay: 
http://<<localhost>>/api/generic_assay_data/<<{molecularProfileId}>>

Example study 

https://github.com/cBioPortal/cbioportal-frontend/tree/master/end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay

Example URL
http://<<localhost>>/api/generic_assay_data/lgg_ucsf_2014_test_generic_assay_armlevel_cna

Example output attached as file

[lgg_ucsf_2014_test_generic_assay_armlevel_cna.json.zip](https://github.com/cBioPortal/cbioportal/files/8351976/lgg_ucsf_2014_test_generic_assay_armlevel_cna.json.zip)

**Comment by jagnathan** [comment]
URL for Get Request for Generic Assay:
http://<>/api/generic_assay_data/<<{molecularProfileId}>>?genericAssayStableId=<<ExamplegenericAssayStableID>>

Example study

https://github.com/cBioPortal/cbioportal-frontend/tree/master/end-to-end-test/local/studies/lgg_ucsf_2014_test_generic_assay

Example URL
http://<>/api/generic_assay_data/lgg_ucsf_2014_test_generic_assay_armlevel_cna?genericAssayStableId=1p_status

Example output attached as file. This JSON file is about 18 KB uncompressed and 2 KB compressed.
[lgg_ucsf_2014_test_generic_assay_armlevel_cna_v2.json.zip](https://github.com/cBioPortal/cbioportal/files/8353632/lgg_ucsf_2014_test_generic_assay_armlevel_cna_v2.json.zip)

**Comment by inodb** [comment]
- GET endpoints for meta (1) molecularProfiled (2) Generic Assay ID
- required parameters should prolly be part of URL (depending on how we did that for other enpdoints)

**Comment by jagnathan** [comment]
Updated the data to the new URL format:

http://localhost:8080/api/generic_assay_data/{molecularProfileId}/generic_assay/{genericAssayStableId}

http://localhost:8080/api/generic_assay_data/lgg_ucsf_2014_test_generic_assay_armlevel_cna/generic_assay/1p_status

**Comment by jagnathan** [comment]
Added new Get endpoint for Generic Assay Meta 

/generic_assay_meta/{molecularProfileId}/generic_assay/{genericAssayStableId}

http://localhost:8080/api/generic_assay_meta/lgg_ucsf_2014_test_generic_assay_armlevel_cna/generic_assay/1p_status

Result:
[{"stableId":"1p_status","entityType":"GENERIC_ASSAY","genericEntityMetaProperties":{"DESCRIPTION":"Copy number status of 1p","NAME":"1p"}}]

**Comment by jagnathan** [comment]
Added new Get endpoint for Generic Assay Meta

/generic_assay_meta/{molecularProfileId}

http://localhost:8080/api/generic_assay_meta/lgg_ucsf_2014_test_generic_assay_armlevel_cna/generic_assay/1p_status
[lgg_ucsf_2014_test_generic_assay_armlevel_cna 2.json.zip](https://github.com/cBioPortal/cbioportal/files/8399965/lgg_ucsf_2014_test_generic_assay_armlevel_cna.2.json.zip)

Response attached.

**Comment by inodb** [comment]
- underscores
- `generic_assay` -> maybe entityId? or something
- need some docs to explain the generic assay vs molecular profile relation
